# config/services.yaml
services:
  # Discord main class
  discord:
    synthetic: true

  Discord\Discord: '@discord'

  # Discord config
  discord_config:
    synthetic: true

  Discord\Config: '@discord_config'

  # Clients
  websocket_client:
    class: Discord\Infrastructure\Websocket\Swoole\WebsocketClient
    arguments:
      - '@discord_config'
      - '@event_dispatcher'
      - '@mapper_service'
    public: true

  Discord\Infrastructure\Websocket\Swoole\WebsocketClient: '@websocket_client'

  http_client:
    class: Discord\Infrastructure\Http\Swoole\HttpClient
    public: true

  Discord\Infrastructure\Http\Swoole\HttpClient: '@http_client'

  # Dispatcher
  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  Symfony\Component\EventDispatcher\EventDispatcher: '@event_dispatcher'

  # Subscribers
  message_subscriber:
    class: Discord\Application\EventSubscriber\MessageSubscriber
    arguments:
      - '@discord_config'
      - '@message_command_service'
    tags: ['event.listener']

  Discord\Application\EventSubscriber\MessageSubscriber: '@message_subscriber'

  command_subscriber:
    class: Discord\Application\EventSubscriber\CommandSubscriber
    arguments:
      - '@channel_send_message_service'
      - '@send_roast_service'
    tags: ['event.listener']

  Discord\Application\EventSubscriber\CommandSubscriber: '@command_subscriber'

  # Services
  mapper_service:
    class: Discord\Application\Service\MapperService

  channel_send_message_service:
    class: Discord\Application\Service\Channel\ChannelSendMessageService
    arguments:
      - '@Discord\Domain\Repository\ChannelRepositoryInterface'
      - '@message_repository'

  send_roast_service:
    class: Discord\Application\Service\Roast\SendRoastService
    arguments:
      - '@channel_send_message_service'

  message_command_service:
    class: Discord\Application\Service\Message\MessageCommandService
    arguments:
      - '@discord_config'
      - '@event_dispatcher'

  # Repositories
  channel_repository:
    class: Discord\Infrastructure\Persistance\Api\ChannelRepository
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@mapper_service'

  message_repository:
    class: Discord\Infrastructure\Persistance\Api\MessageRepository
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@mapper_service'

  user_repository:
    class: Discord\Infrastructure\Persistance\Api\UserRepository
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@mapper_service'

  # Proxy
  channel_repository_proxy:
    class: Discord\Infrastructure\Persistance\Proxy\ChannelRepositoryProxy
    arguments:
      - '@channel_repository'

  Discord\Domain\Repository\ChannelRepositoryInterface: '@channel_repository_proxy'

  user_repository_proxy:
    class: Discord\Infrastructure\Persistance\Proxy\UserRepositoryProxy
    arguments:
      - '@user_repository'

  Discord\Domain\Repository\UserRepositoryInterface: '@user_repository_proxy'