# config/services.yaml
services:

  #Dispatcher
  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  #Subscribers
  message_subscriber:
    class: Discord\Application\EventSubscriber\MessageSubscriber
    arguments:
      - '@discord_config'
      - '@message_command_service'

  Discord\Application\EventSubscriber\MessageSubscriber: '@message_subscriber'

  command_subscriber:
    class: Discord\Application\EventSubscriber\CommandSubscriber
    arguments:
      - '@channel_send_message_service'
      - '@send_roast_service'

  Discord\Application\EventSubscriber\CommandSubscriber: '@command_subscriber'

  #Services
  mapper_service:
    class: Discord\Application\Service\MapperService

  channel_send_message_service:
    class: Discord\Application\Service\Channel\ChannelSendMessageService
    arguments:
      - '@Discord\Domain\Repository\ChannelRepositoryInterface'
      - '@message_repository'

  send_roast_service:
    class: Discord\Application\Service\Roast\SendRoastService
    arguments:
      - '@channel_send_message_service'

  message_command_service:
    class: Discord\Application\Service\Message\MessageCommandService
    arguments:
      - '@discord_config'
      - '@event_dispatcher'

  #Repositories
  channel_repository:
    class: Discord\Infrastructure\Persistance\Api\ChannelRepository
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@mapper_service'

  message_repository:
    class: Discord\Infrastructure\Persistance\Api\MessageRepository
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@mapper_service'

  user_repository:
    class: Discord\Infrastructure\Persistance\Api\UserRepository
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@mapper_service'

  #Proxy
  channel_repository_proxy:
    class: Discord\Infrastructure\Persistance\Proxy\ChannelRepositoryProxy
    arguments:
      - '@channel_repository'

  Discord\Domain\Repository\ChannelRepositoryInterface: '@channel_repository_proxy'

  user_repository_proxy:
    class: Discord\Infrastructure\Persistance\Proxy\UserRepositoryProxy
    arguments:
      - '@user_repository'

  Discord\Domain\Repository\UserRepositoryInterface: '@user_repository_proxy'

  #Clients
  websocket_client:
    class: Discord\Infrastructure\Websocket\Swoole\WebsocketClient
    arguments:
      - '@discord_config'
      - '@event_dispatcher'
      - '@mapper_service'

  http_client:
    class: Discord\Infrastructure\Http\Swoole\HttpClient

  runtime_environment:
    class: Discord\Infrastructure\Environment\SwooleCoroutineRuntimeEnvironment

  discord:
    class: Discord\Discord
    arguments:
      - '@discord_config'
      - '@http_client'
      - '@websocket_client'
      - '@event_dispatcher'
      - '@runtime_environment'

  Discord\Discord: '@discord'

  #Config
  discord_config:
    class: Discord\Config\Config
    arguments:
      - 'https://discordapp.com/api/v6'
      - 'wss://gateway.discord.gg/?v=6&encoding=json'
      - 'NzIyODk3NjgwMDAyNTgwNjIy.Xup6SA.UOqxqtqpzbiF07P-7WZKML6mWzk'
      - '~'


  Discord\Config\Config: '@discord_config'
